# Generated by Django 3.0.4 on 2020-04-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='Images',
        ),
    ]
